---
version: '3'

services:
  postgres:
    image: geographica/postgis:quick_quail
    volumes:
      - ./db/dumps:/var/lib/postgresql/pgdump
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_api
  api:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    container_name: 'django'
    volumes:
      - .:/api
    ports:
      - "8000:8000"
    links:
      - postgres
