# Generated by Django 2.0.7 on 2018-07-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180729_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='updatedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
