# Generated by Django 2.0.7 on 2018-07-30 21:46

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180729_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurence',
            name='position',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
