# Generated by Django 2.0.7 on 2018-07-31 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_occurence_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurence',
            name='status',
            field=models.CharField(choices=[('To_be_validated', 'To be validated'), ('Validated', 'Validated'), ('Solved', 'Solved')], default='To be validated', max_length=255),
        ),
    ]
